### ISSUE TITLE
Missing important tiles

### ISSUE THREAD

**Issue by Plecra** [Lonami/terry#1]
https://github.com/Lonami/terry/blob/d726c23ec87debb74fa4897b5efaaef0ca53a2b2/terraria-protocol/src/structures/tile.rs#L4

I've been checking my implementation against terraria_protocol (thanks!) and noticed that your implementation doesn't recognize tiles 435-439 as needing their frames. We probably made the same mistake, with a regex on the list of assignments in `Main.cs` - it turns out Terraria uses a loop for these:

```cs
for (int num = 435; num <= 439; num++) {
    tileFrameImportant[num] = true;
    tileSolidTop[num] = true;
    tileSolid[num] = true;
    tileNoAttach[num] = true;
    tileTable[num] = true;
    tileLavaDeath[num] = true;
    tileNoSunLight[num] = false;
}
```

**Comment by Lonami** [comment]
(I had forgotten this repo existed). Thanks for catching that! Would you like to send a pull request?

**Comment by Plecra** [comment]
:D I thought that might be the case. Sure, I can add my updated list.
